# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Permalinks
permalink:        pretty

# Setup
title:            weixiaobo88.github.io
tagline:          Blog
url:              http://weixiaobo88.github.io/
paginate:         1
baseurl:
author:
  name:           
  url:            
  email:          

# Custom vars
version:          1.0.0
github:           https://github.com/weixiaobo88/
  repo:           https://github.com/weixiaobo88/weixiaobo88.github.io
